---
- name: Install Rust and required toolchain
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install rustup
      raw: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    - name: Set Rust environment
      raw: source $HOME/.cargo/env
      environment:
        HOME: "{{ ansible_env.HOME }}"

    - name: Install Rust 1.69.0
      raw: rustup install 1.69.0

    - name: Install nightly-2023-02-07 toolchain
      raw: rustup install nightly-2023-02-07-x86_64-unknown-linux-gnu

- name: Install substrate-contracts-node
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Download substrate-contracts-node
      get_url:
        url: "https://github.com/substrate-developer-hub/substrate-contracts-node/releases/download/v0.26.0/substrate-contracts-node-v0.26.0.tar.gz"
        dest: "/tmp/substrate-contracts-node-v0.26.0.tar.gz"

    - name: Extract substrate-contracts-node
      unarchive:
        src: "/tmp/substrate-contracts-node-v0.26.0.tar.gz"
        dest: "/usr/local/bin"
        remote_src: yes
        creates: "/usr/local/bin/substrate-contracts-node"

- name: Install cargo-contract
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install cargo-contract
      raw: cargo install --force --locked cargo-contract --version 3.0.1

- name: Verify versions
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check Rust version
      raw: rustup show

    - name: Check substrate-contracts-node version
      raw: substrate-contracts-node --version

    - name: Check cargo-contract version
      raw: cargo contract --version
